### ISSUE TITLE
secure ldap "Could not initiate TLS connection: Can't contact LDAP server."

### ISSUE THREAD

**Issue by qiwwwwwww** [alexpozzi/pimcore-ldap-bundle#12]
Hi Alex, does your bundle work with secure ldap as well? I got "Could not initiate TLS connection: Can't contact LDAP server." error when I used secure ldap. It works fine for non-secure one.
Btw, I use the latest Pimcore(v6.5), if it helps. 
Thanks.

**Comment by qiwwwwwww** [comment]
I figured it out as the encryption for server is 'ssl'. Sorry for interrupt and thanks for wonderful package:)

**Comment by alexpozzi** [comment]
No problem at all, thanks for the update :wink:
