### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by alexpozzi** [alexpozzi/pimcore-ldap-bundle#13]
Hello,
Last year I changed my job and I don't get to use Pimcore anymore.
As this project is actively used by different companies/developers it would be a shame to let it die because of the reason above.

Please reply to this issue if you are interested in maintaining the project!

**Comment by BlackbitDevs** [comment]
We are a Pimcore agency and gold partner. We develop digitalization strategies for our customers and also put a lot of effort in developing Pimcore plugins and also contribute lots of pull requests to Pimcore core. If you want we could take over to maintain this bundle.

**Comment by alexpozzi** [comment]
That is very kind of you! 
I'm gonna grant you full control over this repository.
If you prefer we can publish it also under a different pseudo like `name_of_your_company/ldap-bundle`, no problem at all from my side :wink:.

**Comment by BlackbitDevs** [comment]
It would be nice if we could publish the package under `BlackbitDigitalCommerce/pimcore-ldap-bundle`. Currently I do not see the settings tab for this repository. I think I only have push permission but not the permission to edit repository settings.

**Comment by alexpozzi** [comment]
I'm gonna have a look later to transfer the repository to your company account so you'll be able to manage it yourself (on Packagist as well).
Is @BlackbitNeueMedien your company account?

Once the new package will be published on Packagist I will deprecate mine and suggest yours as a substitution.

**Comment by BlackbitDevs** [comment]
Yes, @BlackbitNeueMedien is our company account, `BlackbitDigitalCommerce` is our organization.

**Comment by BlackbitDevs** [comment]
@alexpozzi I only want to ensure that you have not forgotten us ;-)  Could you please transfer this repo to our account?

**Comment by alexpozzi** [comment]
Sorry, tough week, I'm gonna do it today, promised :wink:

**Comment by alexpozzi** [comment]
@BlackbitNeueMedien you need to delete your repository fork or else I can't transfer it.
Please ping me when you've done it.

**Comment by BlackbitDevs** [comment]
@alexpozzi I deleted our fork.

**Comment by alexpozzi** [comment]
I've requested the repository transfer. Let me know when you'll publish the new Packagist package so I'll deprecate mine.

Thanks!

**Comment by BlackbitDevs** [comment]
The transfer worked fine and I added the new package to packagist: https://packagist.org/packages/blackbit_digital_commerce/pimcore-ldap

**Comment by alexpozzi** [comment]
I deprecated the former package on Packagist in favor of yours :wink: 
Don't hesitate to ping me for code reviews in case, I'd be happy to help!
