### ISSUE TITLE
[BUG] Conflict with Pimcore 10.1

### ISSUE THREAD

**Issue by dpfahlbusch** [alexpozzi/pimcore-ldap-bundle#18]
Currently this bundle conflicts with Pimcore 10.1, because it requires "symfony/symfony" and Pimcore 10.1 conflicts with "symfony/symfony: *"

**Comment by BlackbitDevs** [comment]
I removed the explicit requirement for `symfony/smyfony` as this is not necessary afaik. Could you try if version `1.5.1` solves the problem for you?

**Comment by dpfahlbusch** [comment]
Works perfect! thank you :)
