### ISSUE TITLE
Use "pimcore/pimcore" instead of "pimcore/core-version" for composer dependency

### ISSUE THREAD

**Issue by domiha** [alexpozzi/pimcore-ldap-bundle#2]
For the new pimcore version, pimcore is using "pimcore/pimcore" for composer. Currently the console gives following information "Package pimcore/core-version is abandoned, you should avoid using it. Use "pimcore/pimcore" instead.

please fix this in your composer.json

**Comment by alexpozzi** [comment]
I'll hopefully work on it this week (I mean test and fix with the new PimCore's version).
Anyway, if you want/have time, you can create a pull request and I'll be happy to merge it!

Thanks!

**Comment by alexpozzi** [comment]
I made the change required, sorry for the delay!
