### ISSUE TITLE
Users aren't stored as coming from LDAP

### ISSUE THREAD

**Issue by tfarmer00** [alexpozzi/pimcore-ldap-bundle#5]
Users aren't stored as LDAP users in the users table. There's no way to differentiate which users were created in Pimcore vs LDAP.

**Comment by alexpozzi** [comment]
From the project `README.md` file: 

You can configure default roles that are gonna be automatically added to every imported LDAP user.
> default_roles: List of Pimcore's roles you wish to give to a user fetched from the LDAP server (example: ['ROLE_LDAP_USERS']). All the configured default roles needs to be already present in Pimcore.

If this is not enough for you, you can implement your own mapper to set specific user attributes.
> mapper: Data mapper service used to map ldap user data to Pimcore user (required, default: Alep\LdapBundle\DataMapper\DefaultLdapUserMapper). See Custom data mapper to build your own data mapper.
