### ISSUE TITLE
Query user's groups in LDAP - if user in group, assign to role in Pimcore

### ISSUE THREAD

**Issue by tfarmer00** [alexpozzi/pimcore-ldap-bundle#7]
Can the functionality be extended, such that if a user is found to be in a particular LDAP group, they are automatically assigned to a matching role in Pimcore?

**Comment by alexpozzi** [comment]
Yes, you can write your own [data mapper](https://github.com/alexpozzi/pimcore-ldap-bundle#custom-data-mapper) and use that instead of the default one.
